esi-catalog:
  build: ../microservice-demo/microservice-demo-catalog
esi-order:
  build: ../microservice-demo/microservice-demo-order
esi-varnish:
  build: varnish
  links:
   - esi-order
   - esi-catalog
  ports:
   - "8080:8080"

